In [2]:
import pandas as pd
import numpy as np
import time


numOfRows = 1000
# append
startTime = time.perf_counter()
df1 = pd.DataFrame(np.random.randint(100, size=(5,5)), columns=['A', 'B', 'C', 'D', 'E'])
for i in range( 1,numOfRows-4):
    df1 = df1.append( dict( (a,np.random.randint(100)) for a in ['A','B','C','D','E']), ignore_index=True)
print('Elapsed time: {:6.3f} seconds for {:d} rows'.format(time.perf_counter() - startTime, numOfRows))
print(df1.shape)

# .loc w/o prealloc
startTime = time.perf_counter()
df2 = pd.DataFrame(np.random.randint(100, size=(5,5)), columns=['A', 'B', 'C', 'D', 'E'])
for i in range( 1,numOfRows):
    df2.loc[i]  = np.random.randint(100, size=(1,5))[0]
print('Elapsed time: {:6.3f} seconds for {:d} rows'.format(time.perf_counter() - startTime, numOfRows))
print(df2.shape)

# .loc with prealloc
df3 = pd.DataFrame(index=np.arange(0, numOfRows), columns=['A', 'B', 'C', 'D', 'E'] )
startTime = time.perf_counter()
for i in range( 1,numOfRows):
    df3.loc[i]  = np.random.randint(100, size=(1,5))[0]
print('Elapsed time: {:6.3f} seconds for {:d} rows'.format(time.perf_counter() - startTime, numOfRows))
print(df3.shape)

# dict
startTime = time.perf_counter()
row_list = []
for i in range (0,5):
    row_list.append(dict( (a,np.random.randint(100)) for a in ['A','B','C','D','E']))
for i in range( 1,numOfRows-4):
    dict1 = dict( (a,np.random.randint(100)) for a in ['A','B','C','D','E'])
    row_list.append(dict1)

df4 = pd.DataFrame(row_list, columns=['A','B','C','D','E'])
print('Elapsed time: {:6.3f} seconds for {:d} rows'.format(time.perf_counter() - startTime, numOfRows))
print(df4.shape)

Elapsed time:  1.429 seconds for 1000 rows
(1000, 5)
Elapsed time:  1.904 seconds for 1000 rows
(1000, 5)
Elapsed time:  0.123 seconds for 1000 rows
(1000, 5)
Elapsed time:  0.019 seconds for 1000 rows
(1000, 5)


In [12]:
#dataset = pd.DataFrame(columns=['review', 'token'])
orig_reviews = []

orig_reviews.append(['abc',1])
orig_reviews.append(['abcs',1])
orig_reviews

[['abc', 1], ['abcs', 1]]

In [13]:
dataset=pd.DataFrame(orig_reviews, columns=['review', 'token'])
dataset

review  token
0    abc      1
1   abcs      1

In [23]:
' '.join(['bought', 'brand', 'disc'])

'bought brand disc'

In [32]:
word_index_map={}
k=['bought', 'brand', 'disc','bought']
k=set(k)
' '.join(k)

'bought brand disc'

In [37]:
X=['I love to play cricket','Cricket is not football','But football is better than hockey']
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2000)
X = cv.fit_transform(X).toarray()
print(X)
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD()
X = svd.fit_transform(X)
print(X)

[[0 0 1 0 0 0 1 0 1 0 1]
 [0 0 1 1 0 1 0 1 0 0 0]
 [1 1 0 1 1 1 0 0 0 1 0]]
[[ 0.44327506  1.81826041]
 [ 1.47318223  0.65080334]
 [ 2.22635253 -0.79266037]]
