In [41]:

    NoOfPatientDoc = input().strip().split(" ")
    NoOfPatients = int(NoOfPatientDoc[0])
    NoOfDoctors = int(NoOfPatientDoc[1])

    counter = 1
    DocEfforts = []
    RowEach = []

    while (counter <= NoOfDoctors):
        data = input().strip().split(" ")[:NoOfPatients]
        DocEfforts = [int(numeric_string) for numeric_string in data]
        RowEach.append(DocEfforts)
        counter = counter + 1

    sumofEach = []
    l1 = []
    l2 = []

    for row in RowEach:
        # sumofEach.append(min(row))
        # print(RowEach.index(row))
        c_index = RowEach.index(row)
        l1.append(sum(row[c_index:]))
        l2.append(sum(row[:c_index]))
    import numpy as np
    print(min(np.add(l1, l2)))



5 5
1 2 5 2 1
1 1 1 7 5
2 2 9 4 1
1 1 5 4 1
1 3 5 2 1
11


In [107]:
    l1 = []
    l2 = []

In [245]:
cnt1=0
while(cnt1<NoOfDoctors):    
    while(cnt2<NoOfPatients):
        #cnt2=0
        l1.append(sum(RowEach[cnt2][cnt2:]))
        cnt1=cnt1+1
        cnt2=cnt2+1
        #while(cnt2<len(RowEach)):
            #l2.append(sum(RowEach[cnt2:][:cnt1]))
            #cnt2=cnt2+1

        

KeyboardInterrupt: 

In [ ]:
l1

In [ ]:
RowEach[1:][cnt2]row[:cnt1]

In [66]:
cnt1=0
cnt2=0
while(cnt1<NoOfDoctors):
    while(cnt2<NoOfPatients):
        l2.append(min(sum(RowEach[cnt1:][0][cnt2:])))
        cnt2=cnt2+1
    cnt1=cnt1+1

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [ ]:
sum(RowEach[1:][0][1:])

In [ ]:
RowEach[1:][0][1:]

In [318]:
l1=[]

for row in RowEach:
    cnt1=0
    r_index = RowEach.index(row)    
    while(cnt1<NoOfPatients):
        if(sum(row[:cnt1])>0):   
            l1.append(sum(row[:cnt1]))
        cnt1=cnt1+1
        
        
        
print(l1)


[1, 3, 8, 10, 1, 2, 3, 10, 2, 4, 13, 17, 1, 2, 7, 10, 1, 4, 9, 11]


In [316]:

l2=[]
for row in RowEach:
    cnt3=0
    cnt2=0
    cnt1=0
    r_index = RowEach.index(row)
    cnt3=r_index
    while(cnt2<NoOfDoctors):
       
        while(cnt1<NoOfPatients):     
            #if(cnt1==r_index):
               # pass
            #else:
                #l2.append(sum(RowEach[r_index][:cnt1]))
            l2.append(sum(row[cnt1:]))
            cnt3=cnt3-1
            cnt1=cnt1+1
        cnt2=cnt2+1
print(l2)

[10, 8, 3, 1, 15, 13, 12, 5, 18, 16, 5, 1, 11, 10, 9, 1, 12, 11, 8, 3]


In [317]:
import numpy as np
np.add(l1, l2)

array([11, 11, 11, 11, 16, 15, 15, 15, 20, 20, 18, 18, 12, 12, 16, 11, 13,
       15, 17, 14])

In [26]:
l1=[]
l3=[]
ss=0
jj=0

for row in RowEach:
    cnt1=0
    l2=[]
    r_index = RowEach.index(row)
    
    while(cnt1<NoOfPatients):
        #if(sum(row[:cnt1])>0):   
        l1.append(sum(row[:cnt1+1]))
        cnt2=0
        ss=0
        #l3=[]
        while(cnt2<NoOfDoctors):
            #if(cnt2!=r_index):
            ss=sum(RowEach[cnt2][cnt1+1:])
            l3.append(ss)
            #print(ss)
            cnt2=cnt2+1
            
        #print(min(l3))
        cnt1=cnt1+1
        #l2.append(min(l3))
       
       
        
print(l1)
#print(l2)
print(l3)


[2, 4, 6, 8, 3, 4, 6, 9]
[6, 6, 4, 5, 2, 3, 0, 0, 6, 6, 4, 5, 2, 3, 0, 0]


In [8]:
sum(RowEach[1][2+1:])

12

In [6]:
RowEach[3]

[1, 1, 5, 4, 1]

In [376]:
import numpy as np
print(min(np.add(l1, l3)))

ValueError: operands could not be broadcast together with shapes (20,) (4,) 

In [36]:
np.add(l1, l2)

array([11, 11, 11, 11, 11, 15, 15, 15, 15, 15, 18, 18, 18, 18, 18, 11, 11,
       11, 11, 11, 12, 12, 12, 12, 12, 11, 10,  8,  3,  1, 15, 14, 13, 12,
        5, 18, 16, 14,  5,  1, 11, 10,  9,  4,  1, 12, 11,  8,  3,  1])

In [267]:
l1

[11,
 10,
 8,
 3,
 1,
 15,
 14,
 13,
 12,
 5,
 18,
 16,
 14,
 5,
 1,
 11,
 10,
 9,
 4,
 1,
 12,
 11,
 8,
 3,
 1]

In [268]:
l2

[0, 1, 2, 3, 10, 0, 2, 4, 13, 17, 0, 1, 2, 7, 10, 0, 1, 4, 9, 11]

In [403]:
l1=[]
l3=[]
ss=0
jj=0
l4=[]
for row in RowEach:
    cnt1=0
    l2=[]
    r_index = RowEach.index(row)
    
    while(cnt1<NoOfPatients):
        if(sum(row[:cnt1])>0):   
            jj=sum(row[:cnt1])
            l1.append(jj)
            
        cnt2=0
        ss=0
        l3=[]

        while(cnt2<NoOfDoctors):
            if(cnt2!=r_index):
                ss=sum(RowEach[cnt2][cnt1:])
                l3.append(ss)
            cnt2=cnt2+1
            
        #print(min(l3))
        cnt1=cnt1+1
        l2.append(min(l3))
       
       
        
print(l1)
print(l2)
print(l3)
print(l4)


[1, 3, 8, 10, 1, 2, 3, 10, 2, 4, 13, 17, 1, 2, 7, 10, 1, 4, 9, 11]
[11, 10, 8, 3, 1]
[1, 5, 1, 1]
[]


In [38]:
a=np.array([2, 4, 6, 8, 3, 4, 6, 9])
np.repeat(l1,3.0)

array([2, 2, 2, 4, 4, 4, 6, 6, 6, 8, 8, 8, 3, 3, 3, 4, 4, 4, 6, 6, 6, 9,
       9, 9])

In [42]:
l1=[]
l3=[]
ss=0
jj=0

for row in RowEach:
    cnt1=0
    l2=[]
    r_index = RowEach.index(row)
    
    while(cnt1<NoOfPatients):
        #if(sum(row[:cnt1])>0):   
        l1.append(sum(row[:cnt1+1]))
        cnt2=0
        ss=0
        #l3=[]
        while(cnt2<NoOfDoctors):
            #if(cnt2!=r_index):
            ss=sum(RowEach[cnt2][cnt1+1:])
            l3.append(ss)
            #print(ss)
            cnt2=cnt2+1
            
        #print(min(l3))
        cnt1=cnt1+1
        #l2.append(min(l3))
       
       
const= len(l3)/len(l1) 
l2=np.repeat(l1,const)
print(l1)
print(l2)
print(l3)


[1, 3, 8, 10, 11, 1, 2, 3, 10, 15, 2, 4, 13, 17, 18, 1, 2, 7, 11, 12, 1, 4, 9, 11, 12]
[ 1  1  1  1  1  3  3  3  3  3  8  8  8  8  8 10 10 10 10 10 11 11 11 11
 11  1  1  1  1  1  2  2  2  2  2  3  3  3  3  3 10 10 10 10 10 15 15 15
 15 15  2  2  2  2  2  4  4  4  4  4 13 13 13 13 13 17 17 17 17 17 18 18
 18 18 18  1  1  1  1  1  2  2  2  2  2  7  7  7  7  7 11 11 11 11 11 12
 12 12 12 12  1  1  1  1  1  4  4  4  4  4  9  9  9  9  9 11 11 11 11 11
 12 12 12 12 12]
[10, 14, 16, 11, 11, 8, 13, 14, 10, 8, 3, 12, 5, 5, 3, 1, 5, 1, 1, 1, 0, 0, 0, 0, 0, 10, 14, 16, 11, 11, 8, 13, 14, 10, 8, 3, 12, 5, 5, 3, 1, 5, 1, 1, 1, 0, 0, 0, 0, 0, 10, 14, 16, 11, 11, 8, 13, 14, 10, 8, 3, 12, 5, 5, 3, 1, 5, 1, 1, 1, 0, 0, 0, 0, 0, 10, 14, 16, 11, 11, 8, 13, 14, 10, 8, 3, 12, 5, 5, 3, 1, 5, 1, 1, 1, 0, 0, 0, 0, 0, 10, 14, 16, 11, 11, 8, 13, 14, 10, 8, 3, 12, 5, 5, 3, 1, 5, 1, 1, 1, 0, 0, 0, 0, 0]


In [43]:
import numpy as np
print(min(np.add(l2, l3)))

6
