In [2]:
''' Read input from STDIN. Print your output to STDOUT '''
# Use input() to read input from STDIN and use print to write your output to STDOUT


def main():
    import numpy as np
    NoOfPatientDoc = input().strip().split(" ")
    NoOfPatients = int(NoOfPatientDoc[0])
    NoOfDoctors = int(NoOfPatientDoc[1])

    counter = 1
    DocEfforts = []
    RowEach = []
    while (counter <= NoOfDoctors):
        data = input().strip().split(" ")[:NoOfPatients]
        DocEfforts = [int(numeric_string) for numeric_string in data]
        RowEach.append(DocEfforts)
        counter = counter + 1
    l1=[]
    l3=[]
    ss=0


    for row in RowEach:
        cnt1=0
        l2=[]
        

        while(cnt1<NoOfPatients):

            l1.append(sum(row[:cnt1+1]))
            cnt2=0
            ss=0

            while(cnt2<NoOfDoctors):

                ss=sum(RowEach[cnt2][cnt1+1:])
                l3.append(ss)

                cnt2=cnt2+1


            cnt1=cnt1+1



    const= len(l3)/len(l1) 
    l2=np.repeat(l1,const)
    print(min(np.add(l2, l3)))
main()

5 5
1 2 5 2 1
1 1 1 7 5
2 2 9 4 1
1 1 5 4 1
1 3 5 2 1
6


In [18]:
''' Read input from STDIN. Print your output to STDOUT '''
# Use input() to read input from STDIN and use print to write your output to STDOUT



import numpy as np
NoOfPatientDoc = input().strip().split(" ")
NoOfPatients = int(NoOfPatientDoc[0])
NoOfDoctors = int(NoOfPatientDoc[1])

counter = 1
DocEfforts = []
RowEach = []
while (counter <= NoOfDoctors):
    data = input().strip().split(" ")[:NoOfPatients]
    DocEfforts = [int(numeric_string) for numeric_string in data]
    RowEach.append(DocEfforts)
    counter = counter + 1
l1=[]
l3=[]
ss=0


for row in RowEach:
    cnt1=0
    l2=[]
    cnt2=0
    while(cnt1<NoOfPatients and cnt2<NoOfDoctors):

        if(cnt1>cnt2 or cnt2==cnt1==0 ):
            l1.append(sum(row[:cnt1+1]))

        ss=sum(RowEach[cnt2][cnt1+1:])
        l3.append(ss)
        

        if(cnt2>=NoOfDoctors):

            cnt1=cnt1+1
            cnt2=0
            ss=0
        else:
            cnt2=cnt2+1
            ss=0


const= len(l3)/len(l1) 
l2=np.repeat(l1,const)
print(min(np.add(l2, l3)))


5 5
1 2 5 2 1
1 1 1 7 5
2 2 9 4 1
1 1 5 4 1
1 3 5 2 1
11


In [79]:
l1=[]
l3=[]
ss=0


for row in RowEach:
    cnt1=0
    l2=[]


    while(cnt1<NoOfPatients):

        l1.append(sum(row[:cnt1+1]))
        cnt2=0
        ss=0

        while(cnt2<NoOfDoctors):

            ss=sum(RowEach[cnt2][cnt1+1:])
            l3.append(ss)

            cnt2=cnt2+1


        cnt1=cnt1+1



const= len(l3)/len(l1) 
l2=np.repeat(l1,const)
print(min(np.add(l2, l3)))

6


In [88]:
l1=[]
l3=[]
ss=0
Con=0
for row in RowEach:
    cnt1=0
    l2=[]
    cnt2=0
    while(cnt1<NoOfPatients and cnt2<NoOfDoctors):

        if(Con==0):
            l1.append(sum(row[:cnt1+1]))
        Con=1

        ss=sum(RowEach[cnt2][cnt1+1:])
        l3.append(ss)
        cnt2=cnt2+1
        ss=0
        if(cnt2>=NoOfDoctors):

            cnt1=cnt1+1
            cnt2=0
            
            Con=0



const= len(l3)/len(l1) 
l2=np.repeat(l1,const)
print(min(np.add(l2, l3)))


6


In [103]:
l1=[]
l3=[]
ss=0
Con=0
kon=0
cnt1=0
cnt2=0
while(kon<NoOfDoctors and cnt1<NoOfPatients and cnt2<NoOfDoctors):

    if(Con==0):
        l1.append(sum(RowEach[kon][:cnt1+1]))
    Con=1

    ss=sum(RowEach[cnt2][cnt1+1:])
    l3.append(ss)
    cnt2=cnt2+1
    ss=0
    if(cnt2>=NoOfDoctors):

        cnt1=cnt1+1
        cnt2=0
        Con=0
    if(cnt1>=NoOfPatients):
        
        cnt1=0
        kon=kon+1


const= len(l3)/len(l1) 
l2=np.repeat(l1,const)
print(min(np.add(l2, l3)))


6


In [111]:
new=np.array(RowEach)

In [142]:
new

array([[1, 2, 5, 2, 1],
       [1, 1, 1, 7, 5],
       [2, 2, 9, 4, 1],
       [1, 1, 5, 4, 1],
       [1, 3, 5, 2, 1]])

In [137]:
minm=np.array(new).min()
minm

1

In [155]:
new

array([[1, 2, 5, 2, 1],
       [1, 1, 1, 7, 5],
       [2, 2, 9, 4, 1],
       [1, 1, 5, 4, 1],
       [1, 3, 5, 2, 1]])

In [203]:
from itertools import permutations, combinations, accumulate


In [213]:
a=4
D1=combinations([1, 2, 5, 2, 1],a)
D2=combinations([1, 1, 1, 7, 5],a)
D3=combinations([2, 2, 9, 4, 1],a)
D4=combinations([1, 1, 5, 4, 1],a)
D5=combinations([1, 3, 5, 2, 1],a)
for a,b,c,d,e in zip(D1,D2,D3,D4,D5):
  
    print(a,b,c,d,e)

(1, 2, 5, 2) (1, 1, 1, 7) (2, 2, 9, 4) (1, 1, 5, 4) (1, 3, 5, 2)
(1, 2, 5, 1) (1, 1, 1, 5) (2, 2, 9, 1) (1, 1, 5, 1) (1, 3, 5, 1)
(1, 2, 2, 1) (1, 1, 7, 5) (2, 2, 4, 1) (1, 1, 4, 1) (1, 3, 2, 1)
(1, 5, 2, 1) (1, 1, 7, 5) (2, 9, 4, 1) (1, 5, 4, 1) (1, 5, 2, 1)
(2, 5, 2, 1) (1, 1, 7, 5) (2, 9, 4, 1) (1, 5, 4, 1) (3, 5, 2, 1)


In [216]:
perms=permutations([1,2,3,4,5],4)
for i in perms:
  
    print(i)

(1, 2, 3, 4)
(1, 2, 3, 5)
(1, 2, 4, 3)
(1, 2, 4, 5)
(1, 2, 5, 3)
(1, 2, 5, 4)
(1, 3, 2, 4)
(1, 3, 2, 5)
(1, 3, 4, 2)
(1, 3, 4, 5)
(1, 3, 5, 2)
(1, 3, 5, 4)
(1, 4, 2, 3)
(1, 4, 2, 5)
(1, 4, 3, 2)
(1, 4, 3, 5)
(1, 4, 5, 2)
(1, 4, 5, 3)
(1, 5, 2, 3)
(1, 5, 2, 4)
(1, 5, 3, 2)
(1, 5, 3, 4)
(1, 5, 4, 2)
(1, 5, 4, 3)
(2, 1, 3, 4)
(2, 1, 3, 5)
(2, 1, 4, 3)
(2, 1, 4, 5)
(2, 1, 5, 3)
(2, 1, 5, 4)
(2, 3, 1, 4)
(2, 3, 1, 5)
(2, 3, 4, 1)
(2, 3, 4, 5)
(2, 3, 5, 1)
(2, 3, 5, 4)
(2, 4, 1, 3)
(2, 4, 1, 5)
(2, 4, 3, 1)
(2, 4, 3, 5)
(2, 4, 5, 1)
(2, 4, 5, 3)
(2, 5, 1, 3)
(2, 5, 1, 4)
(2, 5, 3, 1)
(2, 5, 3, 4)
(2, 5, 4, 1)
(2, 5, 4, 3)
(3, 1, 2, 4)
(3, 1, 2, 5)
(3, 1, 4, 2)
(3, 1, 4, 5)
(3, 1, 5, 2)
(3, 1, 5, 4)
(3, 2, 1, 4)
(3, 2, 1, 5)
(3, 2, 4, 1)
(3, 2, 4, 5)
(3, 2, 5, 1)
(3, 2, 5, 4)
(3, 4, 1, 2)
(3, 4, 1, 5)
(3, 4, 2, 1)
(3, 4, 2, 5)
(3, 4, 5, 1)
(3, 4, 5, 2)
(3, 5, 1, 2)
(3, 5, 1, 4)
(3, 5, 2, 1)
(3, 5, 2, 4)
(3, 5, 4, 1)
(3, 5, 4, 2)
(4, 1, 2, 3)
(4, 1, 2, 5)
(4, 1, 3, 2)
(4, 1, 3, 5)
(4, 1, 5, 2)

In [223]:
D1=accumulate([2, 2, 2, 2])
D2=accumulate([2, 2, 2, 2])
for i in perms:
  
    print(i)

2
4
6
8


In [221]:
x=np.array([[2, 2, 2, 2],
[3, 1, 2, 3]])
x

array([[2, 2, 2, 2],
       [3, 1, 2, 3]])